# Generated by Django 2.1 on 2018-10-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20181003_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
