# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20181008_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
