# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20181010_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
